services:
  frontend:
    container_name: frontend_container
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    ports:
      - "8443:443"
    restart: unless-stopped
    depends_on:
      - backend
      - game
    networks:
      - transcendence
    env_file:
      - .env
    volumes:
    - ./frontend/src:/app/src
    - ./frontend/certs:/etc/nginx/certs

  backend:
    container_name: backend_container
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    networks:
      - transcendence
    env_file:
      - .env
  
  game:
    container_name: game_container
    build:
      context: .
      dockerfile: ./game/Dockerfile
    ports:
      - "3010:3010"
    depends_on:
      - backend
    networks:
      - transcendence

networks:
  transcendence: