services:
  frontend:
    container_name: frontend_container
    build:
      context: ./frontend
    ports:
      - "8080:8080"
    restart: unless-stopped
    depends_on:
      - backend
    networks:
      - transcendence

  backend:
    container_name: backend_container
    build:
      context: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend/data:/app/data
    networks:
      - transcendence

networks:
  transcendence: