worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile      on;

    server {
        listen 443 ssl;
        server_name frontend_container;

        ssl_certificate /etc/nginx/certs/cert.pem;
        ssl_certificate_key /etc/nginx/certs/key.pem;

        root /usr/share/nginx/html;
        index index.html;

        location / {
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass https://backend_container:3000/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_ssl_verify off;
        }

        location /auth/ {
            proxy_pass https://backend_container:3000/;
            proxy_ssl_verify off;  # désactive la vérif SSL sur le self-signed
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }


        location /auth/google/ {
            proxy_pass https://backend_container:3000/auth/google/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
        }


        location /src/ {
            try_files $uri =404;
        }

        location /pages/ {
            try_files $uri =404;
        }

        location /handlers/ {
            try_files $uri =404;
        }

        location /output.css {
            try_files $uri =404;
        }

        # Proxy WebSocket connections to game server
        location /game-ws {
            proxy_pass https://game_container:3010/;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
            proxy_read_timeout 86400;
        }

        # Proxy WebSocket connections to backend (friends/online status)
        location /webs {
            proxy_pass https://backend_container:3000/webs;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_ssl_verify off;
            proxy_read_timeout 86400;
        }
    }
}
