// requirement/frontend/handlers/language.ts
import { apiBase } from '../src/utils';

export type Language = 'en' | 'fr' | 'es';

type Leaf = string;
interface Messages {
	[key: string]: Leaf | Messages;
}

const FALLBACK: Language = 'en';
const REGISTRY = new EventTarget();
const HANDLERS = new Map<(lang: Language) => void, (event: Event) => void>();

const MESSAGES: Record<Language, Messages> = {
	en: {
	nav: {
		label: 'Main navigation',
		skipToContent: 'Skip to main content',
		languageLabel: 'Change language',
		home: 'Home',
		profile: 'Profile',
		play: 'Play',
		friends: 'Friends',
	login: 'Login',
	logout: 'Logout',
	loginLogout: 'Login/Logout',
	theme: 'Theme',
		themeLight: 'Light',
		themeDark: 'Dark',
	},
		home: { 
			title: '🏓 Pong Game', 
			subtitle: 'Challenge your friends in real time.',
			hero: {
				welcome: 'Welcome to the',
				pongGame: 'PONG GAME',
				description: 'Challenge your friends, climb the leaderboard, and experience the revival of a retro classic rebuilt by students at 42 for the modern web.',
			},
			howBuilt: {
				title: 'How It\'s Built',
				subtitle: 'Core milestones of our development journey',
				serverDocker: {
					title: 'Server with Docker',
					description: 'Application with a robust backend infrastructure using Docker for containerization and deployment. Built for performance, scalability, and real-time communication.',
				},
				websocket: {
					title: 'WebSocket Real-time',
					description: 'Real-time multiplayer gaming powered by WebSocket technology. Instant synchronization between players with low latency communication for competitive gameplay.',
				},
				database: {
					title: 'Database Management',
					description: 'Robust SQLite database with better-sqlite3 for user management, game statistics, and tournament records. Features optimized queries for high performance and real-time data synchronization.',
				},
				gameDev: {
					title: 'Game Development',
					description: 'Play a modern take on the classic Pong game with real-time multiplayer support. Challenge your friends and climb the leaderboard through competitive tournaments.',
				},
				tailwind: {
					title: 'Tailwind CSS Only',
					description: 'Crafted entirely with Tailwind CSS for rapid prototyping, consistent design, and responsive interfaces. Utility-first approach ensures maintainable and scalable styling.',
				},
				security: {
					title: 'Security & 2FA',
					description: 'Keep your data safe with strong encryption and secure authentication. Two-Factor Authentication (2FA) adds an extra layer of security.',
				},
			},
			team: {
				title: 'Our Team',
				description: 'We are students from 42, a computer programming school, collaborating on a group project as part of our academic journey.',
				roles: {
					backDev: 'Back Development',
					gameDev: 'Pong Game Design',
					security: 'Security & Protection',
					uiDesign: 'UI & Visual Design',
				},
			},
		technologies: {
			title: 'Technologies we used',
			frontend: 'Frontend',
			backend: 'Backend',
			language: 'Language :',
			framework: 'Framework :',
			server: 'Server :',
			libraries: 'Libraries',
			lib: {
				apiRequests: 'API Requests',
				socket: 'Socket',
				dynamicDrawing: 'Dynamic drawing (game)',
				browserCompatibility: 'Browser compatibility',
				secureConnection: 'Secure connection',
				readFiles: 'Read files (certificates)',
				dateManagement: 'Date management',
				dataVisualization: 'Data visualization',
				themeComponents: 'Theme & components',
				database: 'Database',
				requestsCORS: 'Requests (CORS)',
				fileReading: 'File reading',
				pathManagement: 'Path management',
				fileUpload: 'File upload',
				randomPasswordGeneration: 'Random password generation',
				passwordHashing: 'Password hashing',
				dataFlow: 'Data flow',
				jsonRequests: 'JSON requests',
				sockets: 'Sockets',
				qrCodeGeneration: 'QR code generation',
				codes2FA: '2FA codes',
			},
		},
			footer: {
				legal: 'Legal',
				terms: 'Terms and Conditions',
				copyright: '© 2025 Pong Game. All rights not reserved.',
			},
		},
		main: {
			alerts: {
				firstLogin: 'Welcome to our Transcendence project! Choose a password to finish your registration!',
				googleDenied: 'Google sign-in denied.',
			},
		},
		common: { cancel: 'Cancel', close: 'Close', copy: 'Copy', download: 'Download', loading: 'Loading…', none: 'None' },
		status: { online: 'Online', offline: 'Offline', pending: 'Pending' },
		alerts: {
			needLogin: 'You must be logged in to do that.',
			userExists: 'Username already taken.',
			passwordMismatch: 'Passwords must match.',
			invalidUsername: 'Enter a valid username (3-30 characters).',
			invalidPassword: 'Enter a valid password (3+ characters).',
			serverMessage: 'Error: {message}',
			twofaUnavailable: '2FA action unavailable right now.',
			loginFailed: 'Login failed: {message}',
			passwordUpdated: 'Password updated successfully.',
			selectFile: 'Please select a file.',
			languageSaved: 'Language updated.',
			missingInput: 'Please fill in the required field.',
			invalidUsernameLength: 'The username must contain between 3 and 30 characters.',

		},
		auth: {
			errors: {
				missingField: 'Required field "{field}" not found.',
				twofa: '2FA error: {message}',
				twofaUnknown: 'Verification failed.',
				loginFailed: 'Login failed: {message}',
				loginFallback: 'Login failed.',
				unexpectedResponse: 'Unexpected response from the server.',
			},
			fields: { name: 'Name', email: 'Email address', password: 'Password' },
		},
		friends: {
			title: 'Find your friends',
			subtitle: 'Manage your friends list and instantly view their profiles.',
			addTitle: 'Add a friend',
			addPlaceholder: "Username",
			addCta: 'Add',
			removeTitle: 'Remove a friend',
			removePlaceholder: 'Username',
			removeCta: 'Remove',
			listTitle: 'My friends',
			profileTitle: 'Selected profile',
			hint: 'Add friends to view their profiles!',
			usernameLabel: 'Username:',
			removeButton: 'Remove {username}',
			alerts: {
				added: 'Friend added!',
				removed: 'Friend removed!',
				pending: '{username} is not friends with you yet.',
				network: 'Network error.',
				invalidAdd: 'Unable to add: invalid username.',
				invalidRemove: 'Unable to remove: invalid username.',
				actionImpossible: "Impossible action !"
			},
			history: {
				title: 'Recent matches with this friend',
				loading: 'Loading…',
				empty: 'No matches played against {username}.',
				error: 'Failed to load match history.',
				loginPrompt: 'Log in to see your match history.',
			},
		},
		profile: {
			pageTitle: 'Profile',
			welcome: 'Welcome',
			loginLabel: 'Name',
			emailLabel: 'Email',
			editButton: 'Edit my profile',
			avatarTitle: 'Your avatar',
			stats: 'Statistics',
			editTitle: 'Edit profile',
			uploadLabel: 'Upload a new avatar:',
			uploadCta: 'Upload my avatar',
			usernameLabel: 'New username',
			usernamePlaceholder: 'New username',
			usernameCta: 'Change username',
			passwordCta: 'Change my password',
			logout: 'Log out',
			loginForm: { title: 'Sign in', name: 'Name', password: 'Password', submit: 'Sign in' },
			registerForm: { title: 'Sign up', name: 'Name', email: 'Email', password: 'Password', submit: 'Sign up' },
			google: 'Sign in with Google',
			history: {
				title: 'Match history:',
				loading: 'Loading…',
				empty: 'No match recorded for {username}.',
				error: 'Failed to load history.',
				loginPrompt: 'Log in to see your history.',
			},
			match: {
				victory: 'Win',
				defeat: 'Loss',
				you: 'Me',
				score: 'Score',
				opponent: 'Opponent',
			},
		},
		twofa: {
			sectionTitle: 'Two-factor authentication',
			enabledLabel: '2FA enabled',
			disabledLabel: 'Enable 2FA',
			regenerate: 'Regenerate recovery codes',
			codeCopied: 'Recovery codes copied !',
			hint: 'Tip: keep your recovery codes safe. Each code can only be used once.',
			confirmDisable: 'Disable two-factor authentication?',
			errors: {
				unavailable: '2FA action unavailable right now.',
				generate: 'Unable to generate the QR code.',
				invalidOtp: 'Invalid one-time password.',
				noCodes: 'Setup validated but no codes were returned. Try regenerating.',
				disable: 'Failed to disable two-factor authentication.',
				regenerate: 'Unable to regenerate codes.',
				empty: 'Response received but no recovery codes.',
				copyFailed: 'Unable to copy recovery codes.',
			},
			setup: {
				title: 'Activate two-factor authentication',
				generating: 'Generating the QR code…',
				instruction: 'Scan the QR code with your authenticator app, then enter a 6-digit code to finish activation.',
				otpPlaceholder: '6-digit code',
				activate: 'Activate',
				codesTitle: 'Recovery codes',
				codesInfoSetup: '2FA enabled. Save these recovery codes — they will not be shown again.',
				codesInfoRegen: 'New codes generated. Copy them and keep them safe.',
			},
			prompt: {
				title: 'Two-step verification',
				modeLabel: 'Code type',
				otpOption: '6-digit code',
				recoveryOption: 'Recovery code',
				valueLabel: 'Enter your code',
				cancel: 'Cancel',
				submit: 'Continue',
			},
			buttons: { copy: 'Copy', close: 'Close', download: 'Download' },
			messages: {
				generating: 'Generating the QR code…',
				instruction: 'Scan the QR code then enter a 6-digit code to finish activation.',
				invalidOtp: 'Invalid one-time password.',
			},
		},
		play: {
			title: 'Play Pong',
			chooseMode: 'Choose a game mode',
			localBtn: '2 players on 1 PC',
			onlineBtn: 'Online',
			onlineTitle: 'Online',
			localTitle: 'Local',
			resetBtn: 'Reset',
			quickBtn: 'Quick match',
			tournamentBtn: 'Tournament',
			backBtn: 'Back',
			startOnlineGame: 'Start Online Game',
			startOnlineGameDesc: 'Connect to online matchmaking',
			tournamentTitle: 'Local round-robin tournament',
			closeBtn: 'Close',
			aliasPlaceholder: 'Enter an account name',
			addPlayer: 'Add a player',
			startTournament: 'Start the tournament',
			resetTournament: 'Reset',
			registeredSelf: 'Signed-in player: <strong>{player}</strong> <span class="text-gray-400">(name: {name})</span>',
			registeredOthers: '<strong>Other players:</strong> {list}',
			registeredNone: '<em>No players registered yet</em>',
			standingsTitle: 'Standings',
			tournamentFinished: '🎉 Tournament finished',
			nextMatch: 'Next match: <strong>{player1}</strong> vs <strong>{player2}</strong>',
			launchMatch: 'Play this match',
			gameInProgress: 'Game in progress',
		gameDescription: 'Use the buttons below to control the game',
	startBtn: 'Start',
	pauseBtn: 'Pause',
	playBtn: 'Play',
	waitingForPlayer: 'Waiting for Player...',
	waitingForPlayer2: 'Waiting for player 2...',
	waiting: 'Waiting...',
	restartBtn: 'Restart',
			settingsBtn: 'Settings',
			settingsTitle: 'Game Settings',
			ballSpeed: 'Ball speed',
			ballColor: 'Ball color',
			paddleColor: 'Paddle color',
			ballSize: 'Ball size',
			paddleSize: 'Paddle size',
		small: 'Small',
		normal: 'Normal',
		large: 'Large',
		disabledOnline: 'Disabled in online mode',
		applyBtn: 'Apply',
			gameOver: 'GAME OVER',
			errors: {
				missingAccount: 'This user doesn\'t exist. They need to create an account first.',
				alreadyRegistered: 'This player is already registered.',
				verifyPlayer: 'Error while verifying this player.',
				saveResult: 'Failed to save match result.',
				usernameOnly: 'You entered a username; please provide the account name.',
				needTwoPlayers: 'At least two players are required.',
			},
		},
		enhancedProfile: {
			title: 'Player Dashboard',
			refresh: 'Refresh',
			sessionAnalysis: 'Session Analysis',
			backToProfile: 'Back to Profile',
			loading: 'Loading dashboard data...',
			errorLoading: 'Error loading dashboard',
			errorMessage: 'An error occurred while loading your dashboard data.',
			loginRequired: 'Please log in to view your dashboard',
			userNotFound: 'User information not found',
			profileLabel: 'Profile:',
			winLossTitle: 'Win/Loss Distribution',
			performanceTrendTitle: 'Performance Trend',
			recentMatchesTitle: 'Recent Matches',
			showAll: 'Show All',
			recentOnly: 'Recent Only',
			detailedStatsTitle: 'Detailed Statistics',
			achievementsTitle: 'Achievements',
			insightsTitle: 'Performance Insights',
			cards: {
				winRate: 'Win Rate',
				totalGames: 'Total Games',
				currentStreak: 'Current Streak',
				avgScore: 'Avg Score',
			},
			matchHistory: {
				noMatches: 'No matches found',
				victory: 'Victory',
				defeat: 'Defeat',
				wins: 'Wins',
				losses: 'Losses',
			},
			charts: {
				winRatePercent: 'Win Rate (%)',
				averageScore: 'Average Score',
			},
			statsLabels: {
				totalPointsScored: 'Total Points Scored:',
				totalPointsConceded: 'Total Points Conceded:',
				bestStreak: 'Best Streak:',
				worstStreak: 'Worst Streak:',
				bestScore: 'Best Score:',
				worstScore: 'Worst Score:',
			},
			achievements: {
				dominator: { name: 'Dominator', desc: '80%+ win rate' },
				centurion: { name: 'Centurion', desc: '100+ games played' },
				hotStreak: { name: 'Hot Streak', desc: '10+ win streak' },
				sharpShooter: { name: 'Sharp Shooter', desc: '4+ avg score' },
				consistent: { name: 'Consistent', desc: '60%+ win rate over 50+ games' },
				noAchievements: 'No achievements yet. Keep playing!',
			},
			insights: {
				winningStreak: 'You\'re on a {streak}-game winning streak!',
				losingStreak: 'You\'re on a {streak}-game losing streak. Keep going!',
				excellent: 'Excellent performance! You\'re dominating the competition.',
				needsImprovement: 'Room for improvement. Consider practicing your technique.',
				goodAccuracy: 'Great accuracy! Your scoring is very consistent.',
				improving: 'You\'re improving! Recent performance is better than your average.',
				keepPlaying: 'Keep playing to unlock insights about your performance!',
			},
		},
		sessionDashboard: {
			title: 'Game Session Analysis',
			refresh: 'Refresh',
			backToDashboard: 'Back to Dashboard',
			loading: 'Loading session data...',
			errorLoading: 'Error loading session data',
			errorMessage: 'An error occurred while loading your session data.',
			loginRequired: 'Please log in to view your session data',
			userNotFound: 'User information not found',
			overview: {
				recentWinRate: 'Recent Win Rate',
				lastGames: 'Last {n} games',
				recentAvgScore: 'Recent Avg Score',
				bestRecent: 'Best Recent',
				sessionDuration: 'Session Duration',
				daysActive: 'Days active',
			},
			charts: {
				scoreDistribution: 'Score Distribution',
				performanceByDay: 'Performance by Day',
				recentTrend: 'Recent Performance Trend',
				opponentAnalysis: 'Opponent Analysis',
				frequency: 'Frequency',
				score: 'Score',
				winRate: 'Win Rate (%)',
				avgScore: 'Avg Score',
				result: 'Result',
			},
			matchAnalysis: {
				title: 'Detailed Match Analysis',
				noMatches: 'No matches found',
				victory: 'Victory',
				defeat: 'Defeat',
				scoreLabel: 'Score',
			},
			filters: {
				allTime: 'All Time',
				lastWeek: 'Last Week',
				lastMonth: 'Last Month',
				last3Months: 'Last 3 Months',
				allResults: 'All Results',
				winsOnly: 'Wins Only',
				lossesOnly: 'Losses Only',
			},
			sessionStats: {
				title: 'Session Statistics',
				recentWinRate: 'Recent Win Rate:',
				gamesThisSession: 'Games This Session:',
				bestStreak: 'Best Streak:',
				currentStreak: 'Current Streak:',
			},
			insights: {
				title: 'Performance Insights',
				onFire: 'You\'re on fire! Recent performance is much better than your average.',
				belowAverage: 'Recent performance is below average. Consider taking a break or adjusting your strategy.',
				scoringImproved: 'Your scoring accuracy has improved recently!',
				amazingStreak: 'Amazing winning streak! Keep up the momentum!',
				dontGiveUp: 'Don\'t give up! Every champion has faced setbacks.',
				keepPlaying: 'Keep playing to unlock more insights about your performance!',
			},
			days: {
				sunday: 'Sunday',
				monday: 'Monday',
				tuesday: 'Tuesday',
				wednesday: 'Wednesday',
				thursday: 'Thursday',
				friday: 'Friday',
				saturday: 'Saturday',
			},
		},
		choosePassword: {
			title: 'Set a password',
			labels: { password: 'Password', confirm: 'Confirm password' },
			submit: 'Submit',
			mismatch: 'Passwords do not match.',
			success: 'Password updated successfully!',
			serverError: 'Error while changing the password.',
		},
	},
	fr: {
	nav: {
		label: 'Navigation principale',
		skipToContent: 'Aller au contenu principal',
		languageLabel: 'Changer de langue',
		home: 'Accueil',
		profile: 'Profil',
		play: 'Jeu',
		friends: 'Amis',
	login: 'Connexion',
	logout: 'Déconnexion',
	loginLogout: 'Connexion/Déconnexion',
	theme: 'Thème',
		themeLight: 'Clair',
		themeDark: 'Sombre',
	},
		home: { 
			title: '🏓 Jeu de Pong', 
			subtitle: 'Défie tes amis en temps réel.',
			hero: {
				welcome: 'Bienvenue au',
				pongGame: 'JEU DE PONG',
				description: 'Défie tes amis, grimpe au classement et découvre la renaissance d\'un classique rétro reconstruit par des étudiants de 42 pour le web moderne.',
			},
			howBuilt: {
				title: 'Comment c\'est construit',
				subtitle: 'Étapes clés de notre parcours de développement',
				serverDocker: {
					title: 'Serveur avec Docker',
					description: 'Application avec une infrastructure backend robuste utilisant Docker pour la conteneurisation et le déploiement. Conçue pour la performance, l\'évolutivité et la communication en temps réel.',
				},
				websocket: {
					title: 'WebSocket Temps Réel',
					description: 'Jeu multijoueur en temps réel propulsé par la technologie WebSocket. Synchronisation instantanée entre joueurs avec communication à faible latence pour un gameplay compétitif.',
				},
				database: {
					title: 'Gestion de Base de Données',
					description: 'Base de données SQLite robuste avec better-sqlite3 pour la gestion des utilisateurs, les statistiques de jeu et les records de tournois. Requêtes optimisées pour haute performance et synchronisation des données en temps réel.',
				},
				gameDev: {
					title: 'Développement du Jeu',
					description: 'Jouez à une version moderne du classique Pong avec support multijoueur en temps réel. Défiez vos amis et grimpez au classement à travers des tournois compétitifs.',
				},
				tailwind: {
					title: 'Tailwind CSS Uniquement',
					description: 'Entièrement conçu avec Tailwind CSS pour un prototypage rapide, un design cohérent et des interfaces réactives. L\'approche utility-first garantit un style maintenable et évolutif.',
				},
				security: {
					title: 'Sécurité & 2FA',
					description: 'Protégez vos données avec un chiffrement fort et une authentification sécurisée. L\'authentification à deux facteurs (2FA) ajoute une couche de sécurité supplémentaire.',
				},
			},
			team: {
				title: 'Notre Équipe',
				description: 'Nous sommes des étudiants de 42, une école de programmation informatique, collaborant sur un projet de groupe dans le cadre de notre parcours académique.',
				roles: {
					backDev: 'Développement Back',
					gameDev: 'Design du Jeu Pong',
					security: 'Sécurité & Protection',
					uiDesign: 'Design UI & Visuel',
				},
			},
		technologies: {
			title: 'Technologies utilisées',
			frontend: 'Frontend',
			backend: 'Backend',
			language: 'Langage :',
			framework: 'Framework :',
			server: 'Serveur :',
			libraries: 'Bibliothèques',
			lib: {
				apiRequests: 'Requêtes API',
				socket: 'Socket',
				dynamicDrawing: 'Dessin dynamique (jeu)',
				browserCompatibility: 'Compatibilité navigateur',
				secureConnection: 'Connexion sécurisée',
				readFiles: 'Lecture fichiers (certificats)',
				dateManagement: 'Gestion des dates',
				dataVisualization: 'Visualisation de données',
				themeComponents: 'Thème & composants',
				database: 'Base de données',
				requestsCORS: 'Requêtes (CORS)',
				fileReading: 'Lecture de fichiers',
				pathManagement: 'Gestion des chemins',
				fileUpload: 'Upload fichiers',
				randomPasswordGeneration: 'Génération MDP aléatoire',
				passwordHashing: 'Hashage MDP',
				dataFlow: 'Flux de données',
				jsonRequests: 'Requêtes JSON',
				sockets: 'Sockets',
				qrCodeGeneration: 'Génération QR code',
				codes2FA: 'Codes 2FA',
			},
		},
			footer: {
				legal: 'Mentions légales',
				terms: 'Conditions générales',
				copyright: '© 2025 Jeu de Pong. Tous droits non réservés.',
			},
		},
		main: {
			alerts: {
				firstLogin: 'Bienvenue dans notre projet Transcendance ! Choisis un mot de passe pour finaliser ton inscription !',
				googleDenied: 'Connexion via Google refusée.',
			},
		},
		common: { cancel: 'Annuler', close: 'Fermer', copy: 'Copier', download: 'Télécharger', loading: 'Chargement…', none: 'Aucun' },
		status: { online: 'En ligne', offline: 'Hors ligne', pending: 'en attente' },
		alerts: {
			needLogin: 'Vous devez être connecté pour faire ça',
			userExists: "Nom d’utilisateur déjà utilisé",
			passwordMismatch: 'Les mots de passe doivent correspondre',
			invalidUsername: 'Entrez un nom d’utilisateur valide (3 - 30 caractères)',
			invalidPassword: 'Entrez un mot de passe valide (3+ caractères)',
			serverMessage: 'Erreur : {message}',
			twofaUnavailable: 'Action 2FA impossible pour le moment.',
			loginFailed: 'Erreur : {message}',
			passwordUpdated: 'Mot de passe mis à jour avec succès',
			selectFile: 'Veuillez sélectionner un fichier',
			languageSaved: 'Langue mise à jour.',
			missingInput: 'Veuillez renseigner le champ requis.',
			invalidUsernameLength: 'Le nom d’utilisateur doit contenir entre 3 et 30 caractères.',
		},
		auth: {
			errors: {
				missingField: 'Champ « {field} » introuvable.',
				twofa: 'Erreur 2FA : {message}',
				twofaUnknown: 'Vérification échouée',
				loginFailed: 'Erreur : {message}',
				loginFallback: 'Connexion échouée',
				unexpectedResponse: 'Réponse inattendue du serveur.',
			},
			fields: { name: 'nom', email: 'adresse e-mail', password: 'mot de passe' },
		},
		friends: {
			title: 'Retrouve tes amis',
			subtitle: 'Gère ta liste d’amis et découvre leurs profils en un clin d’œil.',
			addTitle: 'Ajouter un ami',
			addPlaceholder: 'Nom d’utilisateur',
			addCta: 'Ajouter',
			removeTitle: 'Retirer un ami',
			removePlaceholder: 'Nom d’utilisateur',
			removeCta: 'Supprimer',
			listTitle: 'Mes amis',
			profileTitle: 'Profil sélectionné',
			hint: 'Ajoute tes amis pour voir leur profil !',
			usernameLabel: 'Nom d’utilisateur :',
			removeButton: 'Retirer {username}',
			alerts: {
				added: 'Ami ajouté !',
				removed: 'Ami retiré !',
				pending: "{username} n'est pas ami avec toi.",
				network: 'Erreur réseau',
				invalidAdd: "Ajout impossible : nom invalide",
				invalidRemove: "Suppression impossible : nom invalide",
				actionImpossible: "Action impossible !"
			},
			history: {
				title: 'Matchs récents avec cet ami',
				loading: 'Chargement…',
				empty: 'Aucun match joué contre {username}.',
				error: "Impossible de charger l’historique.",
				loginPrompt: 'Connecte-toi pour voir ton historique.',
			},
		},
		profile: {
			pageTitle: 'Profil',
			welcome: 'Bienvenue',
			loginLabel: 'Nom',
			stats: 'Statistiques',
			resetBtn: 'Reinitialiser',
			emailLabel: 'Email',
			editButton: 'Éditer mon profil',
			avatarTitle: 'Votre Avatar',
			editTitle: 'Modifier le Profil',
			uploadLabel: 'Uploader un nouvel avatar :',
			uploadCta: 'Uploader mon avatar',
			usernameLabel: 'Nouvel identifiant',
			usernamePlaceholder: 'Nouvel identifiant',
			usernameCta: "Changer d'identifiant",
			passwordCta: 'Modifier mon mot de passe',
			logout: 'Déconnexion',
			loginForm: { title: 'Connexion', name: 'Nom', password: 'Mot de passe', submit: 'Se connecter' },
			registerForm: { title: 'Inscription', name: 'Nom', email: 'Email', password: 'Mot de passe', submit: "S'inscrire" },
			google: 'Se connecter avec Google',
			history: {
				title: 'Historique des matchs :',
				loading: 'Chargement…',
				empty: 'Aucun match enregistré pour {username}.',
				error: "Erreur de chargement de l’historique.",
				loginPrompt: 'Connecte-toi pour voir ton historique.',
			},
			match: {
				victory: 'Victoire',
				defeat: 'Défaite',
				you: 'Moi',
				score: 'Score',
				opponent: 'Adversaire',
			},
		},
		twofa: {
			sectionTitle: 'Authentification à deux facteurs',
			enabledLabel: '2FA activée',
			disabledLabel: 'Activer le 2FA',
			regenerate: 'Régénérer les codes de récupération',
			codeCopied: 'Codes de récupération copiés !',
			hint: 'Astuce : conserve tes codes de récupération en lieu sûr. Chaque code ne peut être utilisé qu’une seule fois.',
			confirmDisable: 'Désactiver l’authentification à deux facteurs ?',
			errors: {
				unavailable: 'Action 2FA impossible pour le moment.',
				generate: 'Impossible de générer le QR code.',
				invalidOtp: 'OTP invalide.',
				noCodes: 'Configuration validée mais aucun code reçu. Essaie de régénérer.',
				disable: 'Échec désactivation 2FA',
				regenerate: 'Impossible de régénérer les codes.',
				empty: 'Réponse reçue mais aucun code de récupération détecté.',
				copyFailed: 'Impossible de copier les codes de récupération.',
			},
			setup: {
				title: 'Activer l’authentification à deux facteurs',
				generating: 'Génération du QR code…',
				instruction: 'Scanne le QR code avec ton application d’authentification, puis saisis un code à 6 chiffres.',
				otpPlaceholder: 'Code à 6 chiffres',
				activate: 'Activer',
				codesTitle: 'Codes de récupération',
				codesInfoSetup: '2FA activée. Sauvegarde ces codes — ils ne seront pas ré-affichés.',
				codesInfoRegen: 'Nouveaux codes générés. Copie-les et garde-les en lieu sûr.',
			},
			prompt: {
				title: 'Vérification en deux étapes',
				modeLabel: 'Type de code',
				otpOption: 'Code à 6 chiffres',
				recoveryOption: 'Code de récupération',
				valueLabel: 'Entre ton code',
				cancel: 'Annuler',
				submit: 'Continuer',
			},
			buttons: { copy: 'Copier', close: 'Fermer', download: 'Télécharger' },
			messages: {
				generating: 'Génération du QR code…',
				instruction: 'Scanne le QR code puis saisis un code à 6 chiffres pour finaliser l’activation.',
				invalidOtp: 'OTP invalide.',
			},
		},
		play: {
			title: 'Jouer à Pong',
			chooseMode: 'Choisissez un mode de jeu',
			localBtn: '2 joueurs sur 1 PC',
			onlineBtn: 'En ligne',
			onlineTitle: 'En ligne',
			localTitle: 'Local',
			quickBtn: 'Partie rapide',
			tournamentBtn: 'Tournoi',
			backBtn: 'Retour',
			startOnlineGame: 'Lancer Partie En Ligne',
			startOnlineGameDesc: 'Se connecter au matchmaking en ligne',
			tournamentTitle: 'Tournoi round-robin (local)',
			closeBtn: 'Fermer',
				aliasPlaceholder: 'Entrez un nom de compte',
				addPlayer: 'Ajouter un joueur',
				startTournament: 'Lancer le tournoi',
				resetTournament: 'Réinitialiser',
				registeredSelf: 'Joueur connecté : <strong>{player}</strong> <span class="text-gray-400">(nom : {name})</span>',
				registeredOthers: '<strong>Autres joueurs :</strong> {list}',
				registeredNone: '<em>Aucun joueur inscrit</em>',
			standingsTitle: 'Classement',
			tournamentFinished: '🎉 Tournoi terminé',
			nextMatch: 'Prochain match : <strong>{player1}</strong> vs <strong>{player2}</strong>',
			launchMatch: 'Jouer ce match',
			gameInProgress: 'Jeu en cours',
		gameDescription: 'Utilisez les boutons ci-dessous pour contrôler le jeu',
	startBtn: 'Démarrer',
	pauseBtn: 'Pause',
	playBtn: 'Jouer',
	waitingForPlayer: 'En attente d\'un joueur...',
	waitingForPlayer2: 'En attente du joueur 2...',
	waiting: 'En attente...',
	restartBtn: 'Redémarrer',
			settingsBtn: 'Paramètres',
			settingsTitle: 'Paramètres du Jeu',
			ballSpeed: 'Vitesse de la balle',
			ballColor: 'Couleur de la balle',
			paddleColor: 'Couleur des raquettes',
			ballSize: 'Taille de la balle',
			paddleSize: 'Taille des raquettes',
		small: 'Petit',
		normal: 'Normal',
		large: 'Grand',
		disabledOnline: 'Désactivé en mode en ligne',
		applyBtn: 'Appliquer',
			gameOver: 'FIN DE PARTIE',
				errors: {
					missingAccount: "Cet utilisateur n'existe pas. Il doit d'abord créer un compte.",
					alreadyRegistered: 'Ce joueur est déjà inscrit.',
					verifyPlayer: 'Erreur lors de la vérification du joueur.',
					saveResult: 'Enregistrement du match échoué.',
					usernameOnly: 'Vous avez indiqué un identifiant. Merci de fournir le nom de compte.',
					needTwoPlayers: 'Au moins 2 joueurs requis.',
				},
			},
		enhancedProfile: {
			title: 'Tableau de bord joueur',
			refresh: 'Actualiser',
			sessionAnalysis: 'Analyse de session',
			backToProfile: 'Retour au profil',
			loading: 'Chargement des données...',
			errorLoading: 'Erreur de chargement',
			errorMessage: 'Une erreur s\'est produite lors du chargement de vos données.',
			loginRequired: 'Connectez-vous pour voir votre tableau de bord',
			userNotFound: 'Informations utilisateur introuvables',
			profileLabel: 'Profil :',
			winLossTitle: 'Répartition Victoires/Défaites',
			performanceTrendTitle: 'Tendance de performance',
			recentMatchesTitle: 'Matchs récents',
			showAll: 'Tout afficher',
			recentOnly: 'Récents uniquement',
			detailedStatsTitle: 'Statistiques détaillées',
			achievementsTitle: 'Succès',
			insightsTitle: 'Analyses de performance',
			cards: {
				winRate: 'Taux de victoire',
				totalGames: 'Matchs totaux',
				currentStreak: 'Série actuelle',
				avgScore: 'Score moyen',
			},
			matchHistory: {
				noMatches: 'Aucun match trouvé',
				victory: 'Victoire',
				defeat: 'Défaite',
				wins: 'Victoires',
				losses: 'Défaites',
			},
			charts: {
				winRatePercent: 'Taux de victoire (%)',
				averageScore: 'Score moyen',
			},
			statsLabels: {
				totalPointsScored: 'Points totaux marqués :',
				totalPointsConceded: 'Points totaux encaissés :',
				bestStreak: 'Meilleure série :',
				worstStreak: 'Pire série :',
				bestScore: 'Meilleur score :',
				worstScore: 'Pire score :',
			},
			achievements: {
				dominator: { name: 'Dominateur', desc: '80%+ de victoires' },
				centurion: { name: 'Centurion', desc: '100+ matchs joués' },
				hotStreak: { name: 'Série chaude', desc: '10+ victoires consécutives' },
				sharpShooter: { name: 'Tireur d\'élite', desc: '4+ de score moyen' },
				consistent: { name: 'Régulier', desc: '60%+ de victoires sur 50+ matchs' },
				noAchievements: 'Pas encore de succès. Continue à jouer !',
			},
			insights: {
				winningStreak: 'Tu es sur une série de {streak} victoires !',
				losingStreak: 'Tu es sur une série de {streak} défaites. Continue !',
				excellent: 'Performance excellente ! Tu domines la compétition.',
				needsImprovement: 'Piste d\'amélioration. Envisage de pratiquer ta technique.',
				goodAccuracy: 'Excellente précision ! Ton score est très régulier.',
				improving: 'Tu t\'améliores ! Ta performance récente est meilleure que ta moyenne.',
				keepPlaying: 'Continue à jouer pour débloquer des analyses sur ta performance !',
			},
		},
		sessionDashboard: {
			title: 'Analyse de session de jeu',
			refresh: 'Actualiser',
			backToDashboard: 'Retour au tableau de bord',
			loading: 'Chargement des données de session...',
			errorLoading: 'Erreur de chargement des données de session',
			errorMessage: 'Une erreur s\'est produite lors du chargement de vos données de session.',
			loginRequired: 'Connectez-vous pour voir vos données de session',
			userNotFound: 'Informations utilisateur introuvables',
			overview: {
				recentWinRate: 'Taux de victoire récent',
				lastGames: '{n} derniers matchs',
				recentAvgScore: 'Score moyen récent',
				bestRecent: 'Meilleur récent',
				sessionDuration: 'Durée de session',
				daysActive: 'Jours actifs',
			},
			charts: {
				scoreDistribution: 'Distribution des scores',
				performanceByDay: 'Performance par jour',
				recentTrend: 'Tendance de performance récente',
				opponentAnalysis: 'Analyse des adversaires',
				frequency: 'Fréquence',
				score: 'Score',
				winRate: 'Taux de victoire (%)',
				avgScore: 'Score moyen',
				result: 'Résultat',
			},
			matchAnalysis: {
				title: 'Analyse détaillée des matchs',
				noMatches: 'Aucun match trouvé',
				victory: 'Victoire',
				defeat: 'Défaite',
				scoreLabel: 'Score',
			},
			filters: {
				allTime: 'Tout le temps',
				lastWeek: 'Dernière semaine',
				lastMonth: 'Dernier mois',
				last3Months: 'Derniers 3 mois',
				allResults: 'Tous les résultats',
				winsOnly: 'Victoires uniquement',
				lossesOnly: 'Défaites uniquement',
			},
			sessionStats: {
				title: 'Statistiques de session',
				recentWinRate: 'Taux de victoire récent :',
				gamesThisSession: 'Matchs cette session :',
				bestStreak: 'Meilleure série :',
				currentStreak: 'Série actuelle :',
			},
			insights: {
				title: 'Analyses de performance',
				onFire: 'Tu es en feu ! Ta performance récente est bien meilleure que ta moyenne.',
				belowAverage: 'Ta performance récente est en dessous de la moyenne. Envisage de faire une pause ou d\'ajuster ta stratégie.',
				scoringImproved: 'Ta précision de tir s\'est améliorée récemment !',
				amazingStreak: 'Incroyable série de victoires ! Continue sur ta lancée !',
				dontGiveUp: 'N\'abandonne pas ! Tous les champions ont connu des revers.',
				keepPlaying: 'Continue à jouer pour débloquer plus d\'analyses sur ta performance !',
			},
			days: {
				sunday: 'Dimanche',
				monday: 'Lundi',
				tuesday: 'Mardi',
				wednesday: 'Mercredi',
				thursday: 'Jeudi',
				friday: 'Vendredi',
				saturday: 'Samedi',
			},
		},
		choosePassword: {
			title: 'Définir un mot de passe',
			labels: { password: 'Mot de passe', confirm: 'Confirmation' },
			submit: 'Valider',
			mismatch: 'Les mots de passe ne correspondent pas.',
			success: 'Mot de passe mis à jour avec succès!',
			serverError: 'Erreur lors du changement du mot de passe',
		},
	},
	es: {
	nav: {
		label: 'Navegación principal',
		skipToContent: 'Ir al contenido principal',
		languageLabel: 'Cambiar idioma',
		home: 'Inicio',
		profile: 'Perfil',
		play: 'Jugar',
		friends: 'Amigos',
	login: 'Iniciar sesión',
	logout: 'Cerrar sesión',
	loginLogout: 'Iniciar/Cerrar sesión',
	theme: 'Tema',
		themeLight: 'Claro',
		themeDark: 'Oscuro',
	},
		home: { 
			title: '🏓 Juego de Pong', 
			subtitle: 'Desafía a tus amigos en tiempo real.',
			hero: {
				welcome: 'Bienvenido al',
				pongGame: 'JUEGO DE PONG',
				description: 'Desafía a tus amigos, escala en la clasificación y experimenta el renacimiento de un clásico retro reconstruido por estudiantes de 42 para la web moderna.',
			},
			howBuilt: {
				title: 'Cómo está construido',
				subtitle: 'Hitos clave de nuestro viaje de desarrollo',
				serverDocker: {
					title: 'Servidor con Docker',
					description: 'Aplicación con una infraestructura backend robusta usando Docker para contenedorización y despliegue. Construida para rendimiento, escalabilidad y comunicación en tiempo real.',
				},
				websocket: {
					title: 'WebSocket Tiempo Real',
					description: 'Juego multijugador en tiempo real impulsado por tecnología WebSocket. Sincronización instantánea entre jugadores con comunicación de baja latencia para juego competitivo.',
				},
				database: {
					title: 'Gestión de Base de Datos',
					description: 'Base de datos SQLite robusta con better-sqlite3 para gestión de usuarios, estadísticas de juego y registros de torneos. Consultas optimizadas para alto rendimiento y sincronización de datos en tiempo real.',
				},
				gameDev: {
					title: 'Desarrollo del Juego',
					description: 'Juega una versión moderna del clásico Pong con soporte multijugador en tiempo real. Desafía a tus amigos y escala en la clasificación a través de torneos competitivos.',
				},
				tailwind: {
					title: 'Solo Tailwind CSS',
					description: 'Creado completamente con Tailwind CSS para prototipado rápido, diseño consistente e interfaces responsivas. El enfoque utility-first asegura estilos mantenibles y escalables.',
				},
				security: {
					title: 'Seguridad & 2FA',
					description: 'Mantén tus datos seguros con cifrado fuerte y autenticación segura. La autenticación de dos factores (2FA) añade una capa extra de seguridad.',
				},
			},
			team: {
				title: 'Nuestro Equipo',
				description: 'Somos estudiantes de 42, una escuela de programación informática, colaborando en un proyecto grupal como parte de nuestro viaje académico.',
				roles: {
					backDev: 'Desarrollo Back',
					gameDev: 'Diseño del Juego Pong',
					security: 'Seguridad & Protección',
					uiDesign: 'Diseño UI & Visual',
				},
			},
		technologies: {
			title: 'Tecnologías que usamos',
			frontend: 'Frontend',
			backend: 'Backend',
			language: 'Lenguaje :',
			framework: 'Framework :',
			server: 'Servidor :',
			libraries: 'Bibliotecas',
			lib: {
				apiRequests: 'Peticiones API',
				socket: 'Socket',
				dynamicDrawing: 'Dibujo dinámico (juego)',
				browserCompatibility: 'Compatibilidad navegador',
				secureConnection: 'Conexión segura',
				readFiles: 'Lectura archivos (certificados)',
				dateManagement: 'Gestión de fechas',
				dataVisualization: 'Visualización de datos',
				themeComponents: 'Tema & componentes',
				database: 'Base de datos',
				requestsCORS: 'Peticiones (CORS)',
				fileReading: 'Lectura de archivos',
				pathManagement: 'Gestión de rutas',
				fileUpload: 'Subida archivos',
				randomPasswordGeneration: 'Generación contraseña aleatoria',
				passwordHashing: 'Hash contraseña',
				dataFlow: 'Flujo de datos',
				jsonRequests: 'Peticiones JSON',
				sockets: 'Sockets',
				qrCodeGeneration: 'Generación código QR',
				codes2FA: 'Códigos 2FA',
			},
		},
			footer: {
				legal: 'Legal',
				terms: 'Términos y Condiciones',
				copyright: '© 2025 Juego de Pong. Todos los derechos no reservados.',
			},
		},
		main: {
			alerts: {
				firstLogin: '¡Bienvenido a nuestro proyecto Transcendence! Elige una contraseña para finalizar tu registro.',
				googleDenied: 'Inicio de sesión con Google denegado.',
			},
		},
		common: { cancel: 'Cancelar', close: 'Cerrar', copy: 'Copiar', download: 'Descargar', loading: 'Cargando…', none: 'Ninguno' },
		status: { online: 'En línea', offline: 'Sin conexión', pending: 'Pendiente' },
		alerts: {
			needLogin: 'Debes iniciar sesión para hacer eso.',
			userExists: 'El nombre de usuario ya está en uso.',
			passwordMismatch: 'Las contraseñas deben coincidir.',
			invalidUsername: 'Introduce un nombre de usuario válido (3-30 caracteres).',
			invalidPassword: 'Introduce una contraseña válida (3+ caracteres).',
			serverMessage: 'Error: {message}',
			twofaUnavailable: 'La acción de 2FA no está disponible por ahora.',
			loginFailed: 'Error al iniciar sesión: {message}',
			passwordUpdated: 'Contraseña actualizada correctamente.',
			selectFile: 'Selecciona un archivo.',
			languageSaved: 'Idioma actualizado.',
			missingInput: 'Completa el campo obligatorio.',
			invalidUsernameLength: 'El nombre de usuario debe contener entre 3 y 30 caracteres.',

		},
		auth: {
			errors: {
				missingField: 'No se encontró el campo obligatorio "{field}".',
				twofa: 'Error de 2FA: {message}',
				twofaUnknown: 'La verificación falló.',
				loginFailed: 'Error al iniciar sesión: {message}',
				loginFallback: 'Inicio de sesión fallido.',
				unexpectedResponse: 'Respuesta inesperada del servidor.',
			},
			fields: { name: 'Nombre', email: 'Correo electrónico', password: 'Contraseña' },
		},
		friends: {
			title: 'Encuentra a tus amigos',
			subtitle: 'Gestiona tu lista de amigos y descubre sus perfiles al instante.',
			addTitle: 'Añadir un amigo',
			addPlaceholder: 'Nombre de usuario',
			addCta: 'Añadir',
			removeTitle: 'Eliminar un amigo',
			removePlaceholder: 'Nombre de usuario',
			removeCta: 'Eliminar',
			listTitle: 'Mis amigos',
			profileTitle: 'Perfil seleccionado',
			hint: '¡Añade amigos para ver sus perfiles!',
			usernameLabel: 'Nombre de usuario:',
			removeButton: 'Eliminar {username}',
			alerts: {
				added: '¡Amigo añadido!',
				removed: '¡Amigo eliminado!',
				pending: '{username} todavía no es tu amigo.',
				network: 'Error de red.',
				invalidAdd: 'No se puede añadir: nombre de usuario no válido.',
				invalidRemove: 'No se puede eliminar: nombre de usuario no válido.',
				actionImpossible: "Acción imposible"
			},
			history: {
				title: 'Partidas recientes con este amigo',
				loading: 'Cargando…',
				empty: 'No hay partidas jugadas contra {username}.',
				error: 'No se pudo cargar el historial.',
				loginPrompt: 'Inicia sesión para ver tu historial.',
			},
		},
		profile: {
			pageTitle: 'Perfil',
			welcome: 'Bienvenido',
			stats: 'Statistico <3',
			loginLabel: 'Nombre',
			emailLabel: 'Correo electrónico',
			editButton: 'Editar mi perfil',
			avatarTitle: 'Tu avatar',
			editTitle: 'Editar perfil',
			uploadLabel: 'Sube un nuevo avatar:',
			uploadCta: 'Subir mi avatar',
			usernameLabel: 'Nuevo nombre de usuario',
			usernamePlaceholder: 'Nuevo nombre de usuario',
			usernameCta: 'Cambiar nombre de usuario',
			passwordCta: 'Cambiar mi contraseña',
			logout: 'Cerrar sesión',
			loginForm: { title: 'Iniciar sesión', name: 'Nombre', password: 'Contraseña', submit: 'Iniciar sesión' },
			registerForm: { title: 'Registrarse', name: 'Nombre', email: 'Correo electrónico', password: 'Contraseña', submit: 'Registrarse' },
			google: 'Iniciar sesión con Google',
			history: {
				title: 'Historial de partidas:',
				loading: 'Cargando…',
				empty: 'No hay partidas registradas para {username}.',
				error: 'Error al cargar el historial.',
				loginPrompt: 'Inicia sesión para ver tu historial.',
			},
			match: {
				victory: 'Victoria',
				defeat: 'Derrota',
				you: 'Yo',
				score: 'Marcador',
				opponent: 'Oponente',
			},
		},
		twofa: {
			sectionTitle: 'Autenticación de dos factores',
			enabledLabel: '2FA activada',
			disabledLabel: 'Activar 2FA',
			regenerate: 'Regenerar códigos de recuperación',
			codeCopied: '¡Códigos de recuperación copiados!',
			hint: 'Consejo: guarda tus códigos de recuperación en un lugar seguro. Cada código solo puede usarse una vez.',
			confirmDisable: '¿Desactivar la autenticación de dos factores?',
			errors: {
				unavailable: 'La acción de 2FA no está disponible por ahora.',
				generate: 'No se pudo generar el código QR.',
				invalidOtp: 'Código de un solo uso no válido.',
				noCodes: 'La configuración se validó pero no se recibieron códigos. Intenta regenerarlos.',
				disable: 'Error al desactivar el 2FA.',
				regenerate: 'No se pudieron regenerar los códigos.',
				empty: 'Respuesta recibida pero sin códigos de recuperación.',
				copyFailed: 'No se pudieron copiar los códigos de recuperación.',
			},
			setup: {
				title: 'Activar la autenticación de dos factores',
				generating: 'Generando el código QR…',
				instruction: 'Escanea el código QR con tu app de autenticación y escribe un código de 6 dígitos.',
				otpPlaceholder: 'Código de 6 dígitos',
				activate: 'Activar',
				codesTitle: 'Códigos de recuperación',
				codesInfoSetup: '2FA activada. Guarda estos códigos: no se volverán a mostrar.',
				codesInfoRegen: 'Nuevos códigos generados. Cópialos y consérvalos en un lugar seguro.',
			},
			prompt: {
				title: 'Verificación en dos pasos',
				modeLabel: 'Tipo de código',
				otpOption: 'Código de 6 dígitos',
				recoveryOption: 'Código de recuperación',
				valueLabel: 'Introduce tu código',
				cancel: 'Cancelar',
				submit: 'Continuar',
			},
			buttons: { copy: 'Copiar', close: 'Cerrar', download: 'Descargar' },
			messages: {
				generating: 'Generando el código QR…',
				instruction: 'Escanea el código QR y luego introduce un código de 6 dígitos para finalizar la activación.',
				invalidOtp: 'Código de un solo uso no válido.',
			},
		},
		play: {
			title: 'Jugar a Pong',
			chooseMode: 'Elige un modo de juego',
			localBtn: '2 jugadores en un PC',
			onlineBtn: 'En línea',
			onlineTitle: 'En línea',
			localTitle: 'Local',
			quickBtn: 'Partida rápida',
			tournamentBtn: 'Torneo',
			backBtn: 'Volver',
			startOnlineGame: 'Iniciar Juego En Línea',
			startOnlineGameDesc: 'Conectarse al matchmaking en línea',
			tournamentTitle: 'Torneo local todos contra todos',
			closeBtn: 'Cerrar',
			resetBtn: 'Reiniciar',
			aliasPlaceholder: 'Introduce un nombre de cuenta',
			addPlayer: 'Añadir un jugador',
			startTournament: 'Iniciar el torneo',
			resetTournament: 'Reiniciar',
			registeredSelf: 'Jugador conectado: <strong>{player}</strong> <span class="text-gray-400">(nombre: {name})</span>',
			registeredOthers: '<strong>Otros jugadores:</strong> {list}',
			registeredNone: '<em>Ningún jugador inscrito</em>',
			standingsTitle: 'Clasificación',
			tournamentFinished: '🎉 Torneo terminado',
			nextMatch: 'Siguiente partido: <strong>{player1}</strong> vs <strong>{player2}</strong>',
			launchMatch: 'Jugar este partido',
			gameInProgress: 'Juego en curso',
		gameDescription: 'Usa los botones de abajo para controlar el juego',
	startBtn: 'Iniciar',
	pauseBtn: 'Pausa',
	playBtn: 'Jugar',
	waitingForPlayer: 'Esperando jugador...',
	waitingForPlayer2: 'Esperando jugador 2...',
	waiting: 'Esperando...',
	restartBtn: 'Reiniciar',
			settingsBtn: 'Ajustes',
			settingsTitle: 'Ajustes del Juego',
			ballSpeed: 'Velocidad de la bola',
			ballColor: 'Color de la bola',
			paddleColor: 'Color de las paletas',
			ballSize: 'Tamaño de la bola',
			paddleSize: 'Tamaño de las paletas',
		small: 'Pequeño',
		normal: 'Normal',
		large: 'Grande',
		disabledOnline: 'Desactivado en modo en línea',
		applyBtn: 'Aplicar',
			gameOver: 'FIN DEL JUEGO',
			errors: {
				missingAccount: 'Este usuario no existe. Primero debe crear una cuenta.',
				alreadyRegistered: 'Este jugador ya está inscrito.',
				verifyPlayer: 'Error al comprobar a este jugador.',
				saveResult: 'Error al guardar el resultado del partido.',
				usernameOnly: 'Ingresaste un nombre de usuario; escribe el nombre de la cuenta.',
				needTwoPlayers: 'Se requieren al menos dos jugadores.',
			},
		},
		enhancedProfile: {
			title: 'Panel del jugador',
			refresh: 'Actualizar',
			sessionAnalysis: 'Análisis de sesión',
			backToProfile: 'Volver al perfil',
			loading: 'Cargando datos...',
			errorLoading: 'Error al cargar',
			errorMessage: 'Se produjo un error al cargar tus datos.',
			loginRequired: 'Inicia sesión para ver tu panel',
			userNotFound: 'Información de usuario no encontrada',
			profileLabel: 'Perfil:',
			winLossTitle: 'Distribución Victorias/Derrotas',
			performanceTrendTitle: 'Tendencia de rendimiento',
			recentMatchesTitle: 'Partidas recientes',
			showAll: 'Mostrar todo',
			recentOnly: 'Solo recientes',
			detailedStatsTitle: 'Estadísticas detalladas',
			achievementsTitle: 'Logros',
			insightsTitle: 'Análisis de rendimiento',
			cards: {
				winRate: 'Tasa de victorias',
				totalGames: 'Partidas totales',
				currentStreak: 'Racha actual',
				avgScore: 'Puntuación media',
			},
			matchHistory: {
				noMatches: 'No se encontraron partidas',
				victory: 'Victoria',
				defeat: 'Derrota',
				wins: 'Victorias',
				losses: 'Derrotas',
			},
			charts: {
				winRatePercent: 'Tasa de victorias (%)',
				averageScore: 'Puntuación media',
			},
			statsLabels: {
				totalPointsScored: 'Puntos totales marcados:',
				totalPointsConceded: 'Puntos totales recibidos:',
				bestStreak: 'Mejor racha:',
				worstStreak: 'Peor racha:',
				bestScore: 'Mejor puntuación:',
				worstScore: 'Peor puntuación:',
			},
			achievements: {
				dominator: { name: 'Dominador', desc: '80%+ de victorias' },
				centurion: { name: 'Centurión', desc: '100+ partidas jugadas' },
				hotStreak: { name: 'Racha caliente', desc: '10+ victorias consecutivas' },
				sharpShooter: { name: 'Tirador de élite', desc: '4+ de puntuación promedio' },
				consistent: { name: 'Consistente', desc: '60%+ de victorias en 50+ partidas' },
				noAchievements: 'Aún no hay logros. ¡Sigue jugando!',
			},
			insights: {
				winningStreak: '¡Estás en una racha de {streak} victorias!',
				losingStreak: 'Estás en una racha de {streak} derrotas. ¡Sigue adelante!',
				excellent: '¡Rendimiento excelente! Estás dominando la competición.',
				needsImprovement: 'Hay margen de mejora. Considera practicar tu técnica.',
				goodAccuracy: '¡Gran precisión! Tu puntuación es muy consistente.',
				improving: '¡Estás mejorando! Tu rendimiento reciente es mejor que tu promedio.',
				keepPlaying: '¡Sigue jugando para desbloquear análisis sobre tu rendimiento!',
			},
		},
		sessionDashboard: {
			title: 'Análisis de sesión de juego',
			refresh: 'Actualizar',
			backToDashboard: 'Volver al panel',
			loading: 'Cargando datos de sesión...',
			errorLoading: 'Error al cargar datos de sesión',
			errorMessage: 'Se produjo un error al cargar tus datos de sesión.',
			loginRequired: 'Inicia sesión para ver tus datos de sesión',
			userNotFound: 'Información de usuario no encontrada',
			overview: {
				recentWinRate: 'Tasa de victorias reciente',
				lastGames: 'Últimos {n} juegos',
				recentAvgScore: 'Puntuación media reciente',
				bestRecent: 'Mejor reciente',
				sessionDuration: 'Duración de sesión',
				daysActive: 'Días activos',
			},
			charts: {
				scoreDistribution: 'Distribución de puntuaciones',
				performanceByDay: 'Rendimiento por día',
				recentTrend: 'Tendencia de rendimiento reciente',
				opponentAnalysis: 'Análisis de oponentes',
				frequency: 'Frecuencia',
				score: 'Puntuación',
				winRate: 'Tasa de victorias (%)',
				avgScore: 'Puntuación media',
				result: 'Resultado',
			},
			matchAnalysis: {
				title: 'Análisis detallado de partidas',
				noMatches: 'No se encontraron partidas',
				victory: 'Victoria',
				defeat: 'Derrota',
				scoreLabel: 'Puntuación',
			},
			filters: {
				allTime: 'Todo el tiempo',
				lastWeek: 'Última semana',
				lastMonth: 'Último mes',
				last3Months: 'Últimos 3 meses',
				allResults: 'Todos los resultados',
				winsOnly: 'Solo victorias',
				lossesOnly: 'Solo derrotas',
			},
			sessionStats: {
				title: 'Estadísticas de sesión',
				recentWinRate: 'Tasa de victorias reciente:',
				gamesThisSession: 'Partidas esta sesión:',
				bestStreak: 'Mejor racha:',
				currentStreak: 'Racha actual:',
			},
			insights: {
				title: 'Análisis de rendimiento',
				onFire: '¡Estás en llamas! Tu rendimiento reciente es mucho mejor que tu promedio.',
				belowAverage: 'Tu rendimiento reciente está por debajo del promedio. Considera tomar un descanso o ajustar tu estrategia.',
				scoringImproved: '¡Tu precisión de tiro ha mejorado recientemente!',
				amazingStreak: '¡Increíble racha de victorias! ¡Mantén el impulso!',
				dontGiveUp: '¡No te rindas! Todos los campeones han enfrentado reveses.',
				keepPlaying: '¡Sigue jugando para desbloquear más análisis sobre tu rendimiento!',
			},
			days: {
				sunday: 'Domingo',
				monday: 'Lunes',
				tuesday: 'Martes',
				wednesday: 'Miércoles',
				thursday: 'Jueves',
				friday: 'Viernes',
				saturday: 'Sábado',
			},
		},
		choosePassword: {
			title: 'Definir una contraseña',
			labels: { password: 'Contraseña', confirm: 'Confirmar contraseña' },
			submit: 'Confirmar',
			mismatch: 'Las contraseñas no coinciden.',
			success: '¡Contraseña actualizada correctamente!',
			serverError: 'Error al cambiar la contraseña.',
		},
	},
};

function traverse(node: Messages | Leaf, trail: string[]): Leaf | undefined {
	let cursor: Messages | Leaf = node;
	for (const segment of trail) {
		if (typeof cursor === 'string') return undefined;
		const next = cursor[segment];
		if (next === undefined) return undefined;
		cursor = next;
	}
	return typeof cursor === 'string' ? cursor : undefined;
}

function interpolate(template: string, vars: Record<string, string>): string {
	return template.replace(/\{([^}]+)\}/g, (_, name) => vars[name] ?? `{${name}}`);
}

export function t(path: string, vars: Record<string, string> = {}): string {
	const segments = path.split('.');
	const raw =
		traverse(MESSAGES[currentLanguage], segments) ??
		traverse(MESSAGES[FALLBACK], segments) ??
		path;
	return interpolate(raw, vars);
}

let currentLanguage: Language = FALLBACK;
(window as any).currentLanguage = FALLBACK; // Expose for shared game components

export function getLanguage(): Language {
	return currentLanguage;
}

export function setLanguage(lang: Language): void {
	if (currentLanguage === lang) return;
	currentLanguage = lang;
	(window as any).currentLanguage = lang; // Expose for shared game components
	document.documentElement.lang = lang;
	REGISTRY.dispatchEvent(new CustomEvent<Language>('languagechange', { detail: lang }));
}

export function detectInitialLanguage(): Language {
	const stored = localStorage.getItem('language');
	if (stored === 'en' || stored === 'fr' || stored === 'es') return stored;
	const browser = navigator.language?.slice(0, 2).toLowerCase();
	if (browser === 'fr') return 'fr';
	if (browser === 'es') return 'es';
	return FALLBACK;
}

export function onLanguageChange(listener: (lang: Language) => void): void {
	const wrapped = (event: Event) => listener((event as CustomEvent<Language>).detail);
	HANDLERS.set(listener, wrapped);
	REGISTRY.addEventListener('languagechange', wrapped);
}

export function offLanguageChange(listener: (lang: Language) => void): void {
	const wrapped = HANDLERS.get(listener);
	if (!wrapped) return;
	REGISTRY.removeEventListener('languagechange', wrapped);
	HANDLERS.delete(listener);
}

export async function updateLanguage(lang: Language, persist = true): Promise<void> {
	if (lang === currentLanguage) {
		if (persist && localStorage.getItem('language') !== lang) {
			localStorage.setItem('language', lang);
		}
		return;
	}

	setLanguage(lang);
	if (!persist) return;

	localStorage.setItem('language', lang);

	const token = localStorage.getItem('token');
	if (!token) return;

	try {
		await fetch(`${apiBase()}/me/language`, {
			method: 'PUT',
			headers: {
				'Content-Type': 'application/json',
				Authorization: `Bearer ${token}`,
			},
			body: JSON.stringify({ language: lang }),
		});
	} catch (err) {
		console.warn('Unable to persist language', err);
	}
}
